# fly.toml app configuration file generated for nodesmp on 2025-10-07T16:23:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodesmp'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
